//Xen2K entry.js file
var RuntimeElement = document.createElement("script");
RuntimeElement.type = "text/javascript";
RuntimeElement.src = "runtime.js";
document.getElementById("mw-content-text").appendChild(RuntimeElement);
var UtilityElement = document.createElement("script");
UtilityElement.type = "text/javascript";
UtilityElement.src = "X2KUtility.js";
document.getElementById("mw-content-text").appendChild(UtilityElement);
var ObjectElement = document.createElement("script");
ObjectElement.type = "text/javascript";
ObjectElement.src = "X2KObject.js";
document.getElementById("mw-content-text").appendChild(ObjectElement);
var ClassElement = document.createElement("script");
ClassElement.type = "text/javascript";
ClassElement.src = "X2KClass.js";
document.getElementById("mw-content-text").appendChild(ClassElement);
var MapElement = document.createElement("script");
MapElement.type = "text/javascript";
MapElement.src = "X2KMap.js";
document.getElementById("mw-content-text").appendChild(MapElement);
var SettingsElement = document.createElement("script");
SettingsElement.type = "text/javascript";
SettingsElement.src = "X2KSettings.js";
document.getElementById("mw-content-text").appendChild(SettingsElement);
var UIElement = document.createElement("script");
UIElement.type = "text/javascript";
UIElement.src = "X2KUI.js";
document.getElementById("mw-content-text").appendChild(UIElement);
